trainer_cfg:
  output_path: "./output/shd/"
  device_num: -1  # -1 means CPU
  batch_size: 512
  num_epochs: 5000
  es_patience: 5

  dataset_cfg:
    path: "../datasets/"
    dataset: "SHD"

    num_samples: -1
    num_output_classes: 20
    train_split: 0.8
    random_seed: 1

    transform_cfg:
      n_time_bins: 100
      time_window: 0
      spatial_factor: 1
      merge_polarities: true
      augmentation_enabled: false
      augmentation_factor: 1
      augmentation_transform: null

  checkpoint_path: "checkpoints/shd.ckpt"

model_cfg:
  network_type: "feed_forward"
  network_cfg:
    # Network architecture config
    hidden_features: 100
    dropout_low: 0.0
    dropout_high: 0.0
    bias: false
    # Neuron and quantization config
    neuron_type_hidden: lif_quant
    neuron_type_out: li_quant
    tau_inv_mem_hidden: 0.01
    tau_inv_mem_output: 0.001
    threshold: 0.01
    dt: 1.0
    quant_cfg.yaml: "config/hardware/ecs_accelerator_quantization.yaml"

  optimizer_cfg:
    optimizer: "Adam"
    lr: 0.08
    lr_scheduling: false
    lr_scheduling_step_size: 10
    lr_scheduling_fac: 0.1
    spikerate_loss_coefficient: 0.0
    weight_decay: 0.0

hardware_cfg.yaml: "config/hardware/ecs_accelerator_hardware.yaml"
